version: "3"

services:
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 3306:3306

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 9090:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql
